name: Build Kotlin Language Server for termux

on:
  push:
    branch:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential python3 curl
          curl -LO https://github.com/termux/termux-create-package/releases/latest/download/termux-create-package
          chmod a+x ./termux-create-package
          ./termux-create-package --help
